version: '3'
services:
  app:
    build: ./app
    environment:
      APP_ENV: dev
      APP_DEBUG: 'True'
    ports:
      - '5000:5000'
    depends_on:
      - db
  db:
    build: ./db
    restart: unless-stopped
    command: mongod --bind_ip_all
    ports:
      - '27017:27017'
    environment:
      MONGODB_DATA_DIR: /data/db
    
  
