version: '3'
services:
  app:
    build: ./app
    environment:
      APP_ENV: dev
      APP_HOST: 0.0.0.0
      APP_PORT: 5000
      APP_DEBUG: 'True'
      MONGODB_DATABASE: tasks
      MONGODB_HOSTNAME: db
    ports:
      - '5000:5000'
    depends_on:
      - db
  db:
    build: ./db
    restart: unless-stopped
    command: mongod --bind_ip_all
    environment :
    #  MONGO_INITDB_ROOT_USERNAME: admin
    #  MONGO_INITDB_ROOT_PASSWORD: admin
    #  MONGO_INITDB_DATABASE: tasks
      MONGODB_DATA_DIR: /data/db
    #volumes:
    #  - ./db/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - '27017:27017'
    
  
