#version of dockert-compose
version: '3'
# services within the docker-compose . In the given docker-compose 2 containers will be started.
#One container for the app(application) ans second one for mongodb
services:
  # app is the folder name
  app:
    build: ./app
    #add volume for source code
    environment:
      APP_ENV: dev
      APP_HOST: 0.0.0.0
      APP_PORT: 5000
      APP_DEBUG: 'True'
      MONGODB_DATABASE: tasks
      MONGODB_HOSTNAME: db
    ports:
      - 5000:5000
    # depends_on will bind this container to the mongodb container
    depends_on:
      - db
  #nginx configuration
  #webserver:
  #  build: ./webserver
  #  ports: 
  #    - 80:80
  #  networks:
  #    - my-network
  #  depends_on:
  #    - app
    #It is VERY important that your config folder does NOT exist on your host first time you’re starting 
    #the container. When you start your container through docker-compose, it will automatically create the folder 
    #and populate it with the contents of the container
    #volumes:
    #  - ./webserver/nginx.conf:/etc/nginx/conf.d/default.conf
    #  - '/Users/abhishek.sharma/Documents/docker-volumes/webserver:/etc/nginx'
    #  - '/Users/abhishek.sharma/Documents/docker-volumes/certificates/webserver:/etc/ssl/private'
  
  db:
    build: ./db
    restart: unless-stopped
    command: mongod --bind_ip_all
    environment :
    #  MONGO_INITDB_ROOT_USERNAME: admin
    #  MONGO_INITDB_ROOT_PASSWORD: admin
    #  MONGO_INITDB_DATABASE: tasks
      MONGODB_DATA_DIR: /data/db
    #volumes:
    #  - ./db/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - '27017:27017'
    #mounts a local drive to the data folder and stores data in here. Even if we remove 
    #image and rebuild it data will be restored from this volume
    # We can make changes to mounted volumes on host system and then start the docker container 
    volumes:
      - '/Users/abhishek.sharma/Documents/docker-volumes/db:/data/db'
  
  
  
    
  
